package jesse.keeblarcraft;

import jesse.keeblarcraft.gui.ClientHandlers;
// import jesse.keeblarcraft.gui.ScreenManager;
// import jesse.keeblarcraft.gui.widgets.TreeWidget;
import jesse.keeblarcraft.Shortcuts.ShortcutManager;
import jesse.keeblarcraft.entity.MAKE_ENTITY_REGISTER;
import jesse.keeblarcraft.entity.ModModelsLayers;
import jesse.keeblarcraft.entity.PorcupineRenderer;
import jesse.keeblarcraft.entity.model.PorcupineModel;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.client.rendering.v1.EntityModelLayerRegistry;
import net.fabricmc.fabric.api.client.rendering.v1.EntityRendererRegistry;



public class KeeblarcraftClient implements ClientModInitializer {

    @Override
    public void onInitializeClient() {
        ShortcutManager.RegisterKeybinds();
        ClientHandlers.RegisterHandlers();

        // ScreenManager.GetInstance();
        // ScreenManager.AddWidget(TreeWidget.class, 10);

        //Temp Client side Model rendering
        EntityRendererRegistry.register(MAKE_ENTITY_REGISTER.PORCUPINE, PorcupineRenderer::new);
        EntityModelLayerRegistry.registerModelLayer(ModModelsLayers.PORCUPINE, PorcupineModel::getTexturedModelData);
    }
}

