package jesse.keeblarcraft.entity;

import jesse.keeblarcraft.CustomItems.ItemManager;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.item.Item;
import net.minecraft.item.SpawnEggItem;

public class SpawnEggItems {
        //spawn egg
    public static final Item PORCUPINE_SPAWN_EGG = new SpawnEggItem(MAKE_ENTITY_REGISTER.PORCUPINE, 0xa54321, 0xa1235, new FabricItemSettings());

    public static void RegisterPorcupineSpawnEgg() {
       ItemManager.RegisterItem("porcupine_spawn_egg", PORCUPINE_SPAWN_EGG);
   }
}
