package jesse.keeblarcraft.datagen;

import java.util.Optional;

import jesse.keeblarcraft.CustomBlocks.BlockManager;
import jesse.keeblarcraft.entity.SpawnEggItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.client.BlockStateModelGenerator;
import net.minecraft.data.client.ItemModelGenerator;
import net.minecraft.data.client.Model;
import net.minecraft.util.Identifier;

public class KeeblarModelProvider extends FabricModelProvider {

    public KeeblarModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockStateModelGenerator blockStateModelGenerator) {
        blockStateModelGenerator.registerSimpleState(BlockManager.GetBlock("faction_base_block"));
    }

    @Override
    public void generateItemModels(ItemModelGenerator itemModelGenerator) {
        itemModelGenerator.register(SpawnEggItems.PORCUPINE_SPAWN_EGG, new Model(
            Optional.of(new Identifier("item/template_spawn_egg")), Optional.empty()));
    }

}
