package jesse.keeblarcraft.CustomBlocks.BlockEntities;

import jesse.keeblarcraft.Keeblarcraft;
import jesse.keeblarcraft.CustomBlocks.BlockManager;
import net.fabricmc.fabric.api.object.builder.v1.block.entity.FabricBlockEntityTypeBuilder;
import net.minecraft.block.entity.BlockEntityType;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

// EVENTUALLY THIS CLASS WILL GET COLLAPSED UNDER @ref BlockManager.java
// However; I don't have the time to figure out how to do this dynamically this second (I'm lazy and doing this
// all in one sitting)
public class BlockEntityRegistration {
    // PLEASE STICK A COMMENT ABOVE EACH REGISTRATION FOR LATER REFERENCE



    // FactionBlockEntity
    public static final BlockEntityType<FactionBlockEntity> FACTION_BLOCK_ENTITY =
        Registry.register(Registries.BLOCK_ENTITY_TYPE, new Identifier(Keeblarcraft.MOD_ID, "faction_block_entity"),
            FabricBlockEntityTypeBuilder.create(FactionBlockEntity::new, BlockManager.GetBlock("faction_base_block")).build());

    public static void RegisterBlockEntities() {
        Keeblarcraft.LOGGER.info("Registering block entities for " + Keeblarcraft.MOD_ID);
    }
}
