package jesse.keeblarcraft;

import jesse.keeblarcraft.Entities.EntityRegistration;
import jesse.keeblarcraft.Entities.ShopKeeperModel;
import jesse.keeblarcraft.gui.ClientHandlers;
import jesse.keeblarcraft.Shortcuts.ShortcutManager;
import jesse.keeblarcraft.Entities.ShopKeeperRenderer;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.client.rendering.v1.EntityModelLayerRegistry;
import net.fabricmc.fabric.api.client.rendering.v1.EntityRendererRegistry;
import net.minecraft.client.render.entity.model.EntityModelLayer;
import net.minecraft.util.Identifier;


public class KeeblarcraftClient implements ClientModInitializer {
    public static final EntityModelLayer SHOP_KEEPER_LAYER = new EntityModelLayer(new Identifier("textures/entity/villager/villager.png"), "VILLAGE_ENTITY_MODEL_LAYER");

    @Override
    public void onInitializeClient() {
        ShortcutManager.RegisterKeybinds();
        ClientHandlers.RegisterHandlers();

        EntityRendererRegistry.register(EntityRegistration.SHOP_KEEPER_ENTITY_TYPE, ShopKeeperRenderer::new);
        EntityModelLayerRegistry.registerModelLayer(SHOP_KEEPER_LAYER, ShopKeeperModel::getTexturedModelData);
    }
}

